
language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiters_availability_test;

node_js:
  - 12

before_script:
  - psql -c 'create database waiters_availability_test;' -U postgres
  - psql -U postgres -d waiters_availability_test -a -f database.sql


services:
  - postgresql;